services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped

    ports:
      # Local host access only. Tailscale users can use SSH port forwarding.
      - "127.0.0.1:13378:80"

    networks:
      - homelab

    volumes:
      - /srv/homelab/appdata/audiobookshelf:/config
      - /srv/homelab/media/audiobooks:/audiobooks
      - /srv/homelab/appdata/audiobookshelf/metadata:/metadata

networks:
  homelab:
    external: true
