services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped

    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: America/New_York

    ports:
      # Local host access only. Tailscale users can use SSH port forwarding.
      - "127.0.0.1:8083:8083"

    networks:
      - homelab

    volumes:
      - /srv/homelab/appdata/calibre-web:/config
      - /srv/homelab/media/ebooks:/books

networks:
  homelab:
    external: true
